FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
MAINTAINER x0rzkov <x0rzkov@protonmail.com>

RUN apt-get update && \
    apt-get install -y sudo \
    build-essential \
    libssl-dev \
    python3-dev \
    python3-pip \
    openssl \
    git

RUN mkdir -p /opt/service /opt/data
WORKDIR /opt/service
RUN pip3 install --upgrade pip

COPY . .
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "./server.py"]

